export default {
  homePage: "/",
  login: "/login",
  registration: "/registration",
  // categories: "/categories/:id",
  categories: "/categories",
  // categories: "/CategoriesPage",
  selectedCategory: "/selectedCategory",
  postItem: "/postItem",
  allItems: "/items",
  singleItem: "/items/:id",
  profile: "/profiles/:id",
  settings: "/settings",
  buyAndSell: "/buyAndSell",
  Availability: "/Availability",
  };
