export default {
  homePage: "/",
  login: "/login",
  registration: "/registration",
  // categories: "/categories/:id",
  categories: "/categories/:id",
  postItem: "/postItem",
  allItems: "/items",
  singleItem: "/items/:id",
  profile: "/profiles/:id",
  settings: "/settings",
  buyAndSell: "/buyAndSell",
  Availability: "/Availability",
  mobileOverview: "/mobileOverview",
};
